# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
    pragma: no-cache
    cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
    expires: 0

  metas:
    title:        "Espace des professionnels du Vignoble dâ€™Alsace"
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
    pragma:	   no-cache

  stylesheets:    [global.css?202201230010, declaration_recolte.css?201711170207, declaration_stock.css?20140613, contrats_vrac.css?202208241610, jquery.ui.css, /components/vins/vins.css?20160919]

  javascripts:    [plugins/jquery.plugins.min.js, plugins/editable-1.3.3.min.js, global.js?202212121215, declaration_recolte.js?202111041038, declaration_stock.js?20140613, form.js?20140613, vrac.js?202303271640, autocomplete.js?20180718]

  has_layout:     true
  layout:         layout
